var mathematics = 75.25;
var biology = 65;
var chemistry = 80;
var physics = 35.45;
var bangla = 99.50;
var sum = mathematics + biology + chemistry + physics + bangla;
var avarage = sum / 5;
avarage = avarage.toFixed(2);
avarage = parseFloat(avarage);
console.log(avarage);